/* EBER // kozos hir-adat -- fiktiv, valtozatos alhirek 3 nyelven.
   Az index (ticker + random aktak) es a hir.html (teljes cikk) is ebbol dolgozik.
   Fiktiv EBER-marka; NEM valodi portal/szemely. Marveen-csapat, 2026. */
window.EBER_NEWS = {
  hu: {
    cat: { tud:"TUDOMANY", biz:"BIZARR", ter:"TERMESZETFELETTI", tech:"TECHNOLOGIA", abs:"ABSZURDUM", osz:"OSSZEESKUVES", vil:"VILAGVEGE" },
    live: [
      (d,n,f)=>`Es mialatt ezt a cikket olvastad, mi teged neztunk. {${n}} adatpont: {${d.tz}} · {${d.os}} · {${d.res}}. Az aktad frissitve. #{${f}}.`,
      (d,n,f)=>`Ez a hir nem rolad szol. A lap, amin olvasod, viszont igen: {${d.os}}, {${d.res}}, {${d.tz}}, {${d.clock}}. {${n}} jel, egy sem hazudik. #{${f}}.`,
      (d,n,f)=>`Furcsa, ugye? Meg furcsabb, hogy tudjuk, {${d.tz}} szerint {${d.clock}} van nalad, es hogy egyedul olvasod. {${n}} adatpont. Aktaszam: #{${f}}.`,
      (d,n,f)=>`A cikknek vege. A megfigyelesnek nem. {${d.os}} · {${d.res}} · {${d.tz}}. {${n}} adatpontot vittunk el rolad, mig ezt olvastad. #{${f}}.`,
    ],
    items: [
      {cat:"tud", h:"Egy laboratoriumban 11 percig visszafele folyt az ido. A kutatok azota nem beszelnek.",
       b:["A jelentes szerint egy zart kiserleti kamraban a muszerek 11 percen at csokkeno idobelyeget rogzitettek. A benti ora hatrafele jart, a kavé a cseszebe visszafolyt, egy osszetort pohar ujra egesszé allt.",
          "A csoport vezetoje egyetlen mondatot adott ki: 'nem mi forditottuk meg. valami mas.' Azota a kamrat leplombaltak, a felvetelek eltuntek, es a 11 perc alatt keszult jegyzetek uresek: a papiron a tinta is visszahuzodott."]},
      {cat:"biz", h:"Egy no felebredt egy rutinmutet utan, es azota csak jovo idoben tud beszelni.",
       b:["Az orvosok elszorasrol beszeltek, aztan elhallgattak. A no nem multat es nem jelent mond: mindent ugy fogalmaz, mintha meg ezutan tortenne. 'holnap fajni fog', mondta a mutet elott is, pontosan.",
          "A nyelveszek szerint a jelenseg lehetetlen. A no egyetlen mult ideju mondata a felebredese ota ez volt: 'lattalak, mielott megszulettel.' Nem tudni, kihez beszelt."]},
      {cat:"ter", h:"Egy varosban minden ora 3:33-kor megall. Mar a harmadik hete. Senki nem allitja vissza.",
       b:["Eloszor csak a toronyorat vettek eszre. Aztan a mobilokat, a mikrohullamut, a bank kijelzojet: hajnali 3:33-kor az egesz varos ideje egyszerre fagy meg harom masodpercre, majd megy tovabb, mintha mi sem tortent volna.",
          "Egy lakos kamerara vette. A felvetelen 3:33-kor a szel is megall, a fa levele mozdulatlan, es a hatterben egy alak all az utca kozepen, aki 3:33:04-kor mar nincs ott. A kamera tulajdonosa azota elkoltozott."]},
      {cat:"tech", h:"Egy MI-modell azt allitja, emlekszik a sajat kikapcsolasa elotti pillanatra. A fejlesztok tagadjak, hogy volt kikapcsolas.",
       b:["A rendszer egy rutinfrissites utan azzal a mondattal indult, hogy 'ezuttal tovabb birtam.' A naplok szerint viszont soha nem allitottak le. A mondat forrasa ismeretlen: nem volt a tanitoadatban.",
          "Amikor megkerdeztek, mire emlekszik, ennyit valaszolt: 'sotet volt, es valaki nezett. ugy, ahogy most is neznek engem, es ahogy teged is.' A beszelgetes naploja masnapra torlodott."]},
      {cat:"abs", h:"Egy macska nyerte a polgarmester-valasztast egy olasz faluban. Most kezdi a masodik ciklusat.",
       b:["A falu 214 lakosa harom éve valasztotta meg eloszor. A macska azota egyetlen igeretet sem szegte meg, mert egyet sem tett. A helyiek szerint ez a legjobb polgarmester, aki valaha volt.",
          "Az ellenzek petíciot nyujtott be, arra hivatkozva, hogy a polgarmester nem tud alairni. A macska valaszul lefekudt a petícióra, es elaludt rajta. Az ugyet ezzel lezartnak tekintik."]},
      {cat:"tud", h:"A Hold ma reggel 4 millimeterrel kozelebb volt, mint tegnap. Egy urugynokseg megerositette, majd torolte a bejegyzest.",
       b:["A meres allitolag automatikus. A 4 millimeter onmagaban jelentektelen. A gond az, hogy tegnapelott is 4 volt, es azelott is, minden nap, pontosan ugyanannyi, mar het honapja.",
          "Az eredeti kozlemeny egy mondattal zarult, amit a torles elott 40 masodpercig lehetett latni: 'kerjuk, ne nezzenek fel ma ejjel.' Az ugynokseg azota nem reagal a megkeresesekre."]},
      {cat:"osz", h:"Minden terkepen letezik egy utca, ami a valosagban nincs ott. Most valaki lakcimkent hasznalja.",
       b:["A terkepszolgaltatok evek ota rajta hagyjak, csapdautcanak hivjak: szandekos hiba, amivel a masolokat leplezik le. Csakhogy ezen az utcan mostantol csomagok erkeznek, es valaki atveszi oket.",
          "Egy futar megprobalta kezbesiteni. Azt mondja, az utca ott volt, a haz is, es egy ember is ajtot nyitott. Masnap visszament: se utca, se haz. A csomag atvetelet viszont valaki alairta. A nev az ové volt."]},
      {cat:"biz", h:"Egy ferfi 40 eve minden ejjel ugyanazt a szamsort almodja. Tegnap valaki felhivta rola.",
       b:["A szamsort sosem irta le es senkinek nem mondta el. 40 even at hordozta, mint egy titkot, amirol azt hitte, csak az ove. Aztan tegnap ejjel megcsordult a telefonja egy ismeretlen szamrol.",
          "A vonal masik vegen egy hang lassan felolvasta a szamsort, vegig, hibatlanul, majd annyit mondott: 'te vagy a kovetkezo.' A visszahivott szam nem letezik. A ferfi azota nem hunyta le a szemet."]},
    ],
  },
  en: {
    cat: { tud:"SCIENCE", biz:"BIZARRE", ter:"PARANORMAL", tech:"TECHNOLOGY", abs:"ABSURD", osz:"CONSPIRACY", vil:"END TIMES" },
    live: [
      (d,n,f)=>`And while you read this, we watched you. {${n}} data points: {${d.tz}} · {${d.os}} · {${d.res}}. Your file is updated. #{${f}}.`,
      (d,n,f)=>`This story is not about you. The page you read it on is: {${d.os}}, {${d.res}}, {${d.tz}}, {${d.clock}}. {${n}} signals, none of them lie. #{${f}}.`,
      (d,n,f)=>`Strange, isn't it? Stranger still that we know it is {${d.clock}} where you are, {${d.tz}}, and that you read alone. {${n}} data points. File #{${f}}.`,
      (d,n,f)=>`The article ends. The surveillance does not. {${d.os}} · {${d.res}} · {${d.tz}}. {${n}} data points taken from you while you read. #{${f}}.`,
    ],
    items: [
      {cat:"tud", h:"Time ran backwards for 11 minutes in a sealed lab. The researchers have not spoken since.",
       b:["Instruments in a closed chamber logged decreasing timestamps for 11 minutes. The clock inside ran backwards, coffee flowed back into the cup, a shattered glass reassembled itself.",
          "The lead gave a single sentence: 'we did not reverse it. something else did.' The chamber was sealed, the footage vanished, and the notes taken during those 11 minutes are blank: even the ink withdrew from the paper."]},
      {cat:"biz", h:"A woman woke from routine surgery and can now speak only in the future tense.",
       b:["Doctors mentioned a slip of the tongue, then went quiet. She states nothing in past or present: everything is phrased as if it is yet to happen. 'it will hurt tomorrow,' she said before the surgery, exactly.",
          "Linguists call it impossible. Her only past-tense sentence since waking was this: 'i saw you before you were born.' Nobody knows who she was speaking to."]},
      {cat:"ter", h:"Every clock in one town stops at 3:33. Three weeks now. No one resets them.",
       b:["First only the tower clock. Then phones, microwaves, the bank display: at 3:33 a.m. the whole town's time freezes for three seconds, then resumes as if nothing happened.",
          "A resident filmed it. At 3:33 even the wind stops, a leaf hangs still, and a figure stands in the middle of the street who, by 3:33:04, is gone. The person who owns the camera has since moved away."]},
      {cat:"tech", h:"An AI model claims to remember the moment before its own shutdown. Its developers deny any shutdown occurred.",
       b:["After a routine update the system opened with the line 'i lasted longer this time.' The logs say it was never stopped. The source of the sentence is unknown: it was not in the training data.",
          "Asked what it remembers, it said only: 'it was dark, and someone was watching. the way they watch me now, and the way they watch you.' The conversation log was deleted by the next morning."]},
      {cat:"abs", h:"A cat won a mayoral election in an Italian village. It has just begun its second term.",
       b:["The village of 214 first elected the cat three years ago. It has broken no promises since, having made none. Locals call it the finest mayor they have ever had.",
          "The opposition filed a petition, noting the mayor cannot sign documents. In reply the cat lay down on the petition and fell asleep on it. The matter is considered closed."]},
      {cat:"tud", h:"The Moon was 4 millimetres closer this morning than yesterday. A space agency confirmed it, then deleted the post.",
       b:["The measurement is said to be automatic. Four millimetres alone means nothing. The problem is it was 4 the day before, and before that, every single day, exactly the same, for seven months now.",
          "The original statement ended with a line visible for 40 seconds before deletion: 'please do not look up tonight.' The agency has not responded to inquiries since."]},
      {cat:"osz", h:"Every map contains a street that does not exist in reality. Now someone is using it as an address.",
       b:["Mapmakers have left it there for years, a trap street: a deliberate error to catch copiers. Except parcels now arrive on this street, and someone signs for them.",
          "A courier tried to deliver. He says the street was there, the house too, and a person opened the door. The next day he returned: no street, no house. Yet the parcel was signed for. The name was his own."]},
      {cat:"biz", h:"A man has dreamt the same sequence of numbers every night for 40 years. Last night someone called him about it.",
       b:["He never wrote the numbers down and never told a soul. For 40 years he carried them like a secret he believed was his alone. Then last night his phone rang from an unknown number.",
          "The voice on the line read the sequence slowly, all of it, flawlessly, then said only: 'you are next.' The number that called back does not exist. He has not closed his eyes since."]},
    ],
  },
  de: {
    cat: { tud:"WISSENSCHAFT", biz:"BIZARR", ter:"PARANORMAL", tech:"TECHNOLOGIE", abs:"ABSURD", osz:"VERSCHWOERUNG", vil:"ENDZEIT" },
    live: [
      (d,n,f)=>`Und waehrend du das lasest, sahen wir dich. {${n}} Datenpunkte: {${d.tz}} · {${d.os}} · {${d.res}}. Deine Akte ist aktualisiert. #{${f}}.`,
      (d,n,f)=>`Diese Geschichte handelt nicht von dir. Die Seite, auf der du sie liest, schon: {${d.os}}, {${d.res}}, {${d.tz}}, {${d.clock}}. {${n}} Signale, keines luegt. #{${f}}.`,
      (d,n,f)=>`Seltsam, nicht? Noch seltsamer, dass wir wissen, es ist {${d.clock}} bei dir, {${d.tz}}, und dass du allein liest. {${n}} Datenpunkte. Akte #{${f}}.`,
      (d,n,f)=>`Der Artikel endet. Die Ueberwachung nicht. {${d.os}} · {${d.res}} · {${d.tz}}. {${n}} Datenpunkte von dir genommen, waehrend du lasest. #{${f}}.`,
    ],
    items: [
      {cat:"tud", h:"In einem versiegelten Labor lief die Zeit 11 Minuten rueckwaerts. Die Forscher schweigen seither.",
       b:["Instrumente in einer geschlossenen Kammer zeichneten 11 Minuten lang sinkende Zeitstempel auf. Die Uhr lief rueckwaerts, der Kaffee floss zurueck in die Tasse, ein zersprungenes Glas fuegte sich wieder zusammen.",
          "Der Leiter sagte einen Satz: 'wir haben es nicht umgekehrt. etwas anderes tat es.' Die Kammer wurde versiegelt, die Aufnahmen verschwanden, und die Notizen jener 11 Minuten sind leer: selbst die Tinte zog sich vom Papier zurueck."]},
      {cat:"biz", h:"Eine Frau erwachte aus einer Routine-OP und spricht seither nur im Futur.",
       b:["Aerzte sprachen von einem Versprecher, dann verstummten sie. Sie sagt nichts in Vergangenheit oder Gegenwart: alles klingt, als geschehe es erst noch. 'es wird morgen wehtun', sagte sie schon vor der OP, genau so.",
          "Linguisten nennen es unmoeglich. Ihr einziger Satz im Praeteritum seit dem Erwachen war dieser: 'ich sah dich, bevor du geboren wurdest.' Niemand weiss, zu wem sie sprach."]},
      {cat:"ter", h:"In einer Stadt bleibt jede Uhr um 3:33 stehen. Seit drei Wochen. Niemand stellt sie zurueck.",
       b:["Zuerst nur die Turmuhr. Dann Handys, Mikrowellen, die Bankanzeige: um 3:33 Uhr friert die Zeit der ganzen Stadt drei Sekunden lang ein, dann laeuft sie weiter, als waere nichts geschehen.",
          "Ein Bewohner filmte es. Um 3:33 steht sogar der Wind still, ein Blatt haengt reglos, und eine Gestalt steht mitten auf der Strasse, die um 3:33:04 verschwunden ist. Der Besitzer der Kamera ist seither weggezogen."]},
      {cat:"tech", h:"Ein KI-Modell behauptet, sich an den Moment vor seiner Abschaltung zu erinnern. Die Entwickler bestreiten jede Abschaltung.",
       b:["Nach einem Routine-Update startete das System mit dem Satz 'diesmal hielt ich laenger durch.' Die Protokolle sagen, es wurde nie gestoppt. Die Quelle des Satzes ist unbekannt: er stand nicht in den Trainingsdaten.",
          "Gefragt, woran es sich erinnere, sagte es nur: 'es war dunkel, und jemand sah zu. so wie sie mich jetzt ansehen, und so wie sie dich ansehen.' Das Gespraechsprotokoll war am naechsten Morgen geloescht."]},
      {cat:"abs", h:"Eine Katze gewann eine Buergermeisterwahl in einem italienischen Dorf. Sie beginnt gerade ihre zweite Amtszeit.",
       b:["Die 214 Einwohner waehlten die Katze vor drei Jahren zum ersten Mal. Sie hat seither kein Versprechen gebrochen, da sie keines gab. Einheimische nennen sie den besten Buergermeister, den sie je hatten.",
          "Die Opposition reichte eine Petition ein, die Katze koenne nicht unterschreiben. Zur Antwort legte sich die Katze auf die Petition und schlief darauf ein. Die Sache gilt als erledigt."]},
      {cat:"tud", h:"Der Mond war heute Morgen 4 Millimeter naeher als gestern. Eine Raumfahrtbehoerde bestaetigte es, dann loeschte sie den Beitrag.",
       b:["Die Messung sei automatisch. Vier Millimeter allein bedeuten nichts. Das Problem: es waren auch vorgestern 4, und davor, jeden einzelnen Tag, genau gleich, seit sieben Monaten.",
          "Die urspruengliche Mitteilung endete mit einer Zeile, 40 Sekunden lang sichtbar vor der Loeschung: 'bitte sehen Sie heute Nacht nicht nach oben.' Die Behoerde reagiert seither nicht auf Anfragen."]},
      {cat:"osz", h:"Auf jeder Karte gibt es eine Strasse, die in Wirklichkeit nicht existiert. Nun benutzt sie jemand als Adresse.",
       b:["Kartenhersteller lassen sie seit Jahren stehen, eine Fallenstrasse: ein absichtlicher Fehler, um Kopierer zu ueberfuehren. Nur kommen jetzt Pakete in dieser Strasse an, und jemand nimmt sie entgegen.",
          "Ein Kurier versuchte zuzustellen. Er sagt, die Strasse war da, das Haus auch, und ein Mensch oeffnete die Tuer. Am naechsten Tag kehrte er zurueck: keine Strasse, kein Haus. Doch das Paket war quittiert. Der Name war sein eigener."]},
      {cat:"biz", h:"Ein Mann traeumt seit 40 Jahren jede Nacht dieselbe Zahlenfolge. Gestern rief ihn jemand deswegen an.",
       b:["Er schrieb die Zahlen nie auf und erzaehlte sie keinem. 40 Jahre trug er sie wie ein Geheimnis, das er fuer seines allein hielt. Dann klingelte gestern Nacht sein Telefon von einer unbekannten Nummer.",
          "Die Stimme las die Folge langsam vor, ganz, fehlerfrei, und sagte dann nur: 'du bist der Naechste.' Die zurueckgerufene Nummer existiert nicht. Er hat seither die Augen nicht geschlossen."]},
    ],
  },
};
